title: Nang Myo Thandar Win 
logo: assests/img/img2.png
description: Software Quality Assurance Engineer
description: Email: myothandarwin98@gmail.com
description: Phone: +66 0627800280
#download_link: assests/img/my_resum.xlsx.docx
#show_downloads: true
theme: jekyll-theme-minimal
